name: (CI) - Building and testing the project 
on:
  workflow_dispatch:
  push: 
    branches: [ main, CHR8486 ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main, CHR8486 ]

jobs:
    assemble:
        runs-on: ubuntu-latest
        env:
            GITHUB_LOGIN: ${{ github.actor }}
            GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        steps:
        -   name: This step creates a copy of the repository for the workflow to run on
            uses: actions/checkout@v3
        -   name: This step sets up java on the machine running this workflow
            uses: actions/setup-java@v3
            with:
                distribution: 'temurin'
                java-version: '16'
            
        -   name: Assembling the gradle project
            run: |
                chmod +x gradlew        
                ./gradlew assemble
    test:
        runs-on: ubuntu-latest
        needs: assemble
        env:
            GITHUB_LOGIN: ${{ github.actor }}
            GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        steps:
        -   name: This step creates a copy of the repository for the workflow to run on
            uses: actions/checkout@v3
        -   name: This step sets up java on the machine running this workflow
            uses: actions/setup-java@v3
            with:
                distribution: 'temurin'
                java-version: '16'
            
        -   name: Testing the gradle project.
            run: |
                chmod +x gradlew        
                ./gradlew test

    notify:
        runs-on: ubuntu-latest
        needs: test
        steps:
        -   name: Email notification
            uses: cinotify/github-action@main
            with:
                to: '${{ secrets.EMAIL }}'
                subject: '[Pipeline in ${{ github.repository }}] Workflow for Sindre has been ran successfully.'
                body: 'The workflow ${{ github.workflow }} in the repository ${{ github.repository }} has been ran successfully by ${{ github.actor }}. The workflow was triggered by ${{ github.event_name }}. The commit message was: ${{ github.event.head_commit.message }}. The commit was pushed by ${{ github.event.head_commit.author.name }}. The commit was pushed at ${{ github.event.head_commit.timestamp }}. The commit was pushed at ${{ github.event.head_commit.url}}.'